import { describe, expect, it } from "vitest";
import { attributionProblems } from "./attribution.mjs";

const commit = (over = {}) => ({
  sha: "0123456789abcdef",
  authorName: "jincheng_m",
  authorEmail: "maintainer@example.com",
  committerName: "jincheng_m",
  committerEmail: "maintainer@example.com",
  message: "fix(cli): something\n\nWhy it changed.\n",
  ...over,
});

describe("attribution check", () => {
  it("passes a clean pull request", () => {
    expect(attributionProblems({ commits: [commit()], body: "Closes #1" })).toEqual([]);
  });

  it("refuses an AI author or committer", () => {
    const problems = attributionProblems({
      commits: [
        commit({ authorName: "Claude", authorEmail: "noreply@anthropic.com" }),
        commit({ committerName: "Claude", committerEmail: "other@example.com" }),
      ],
      body: "",
    });
    expect(problems).toEqual([
      "0123456: author is an AI tool (Claude <noreply@anthropic.com>)",
      "0123456: committer is an AI tool (Claude <other@example.com>)",
    ]);
  });

  it("refuses co-author trailers of any kind", () => {
    const message = "feat: x\n\nCo-Authored-By: Someone <a@example.com>\n";
    expect(attributionProblems({ commits: [commit({ message })], body: "" })).toEqual([
      "0123456: has a Co-authored-by trailer",
    ]);
  });

  it("refuses tool footers in commits and in the description", () => {
    const message = "fix: x\n\nClaude-Session: https://claude.ai/code/session_01ABC\n";
    const body = "Summary\n\n🤖 Generated with [Claude Code](https://claude.com/claude-code)";
    expect(attributionProblems({ commits: [commit({ message })], body })).toEqual([
      "0123456: message has an AI tool's footer",
      "pull request description has an AI tool's footer",
    ]);
    expect(
      attributionProblems({
        commits: [],
        body: "_Generated by [Claude Code](https://claude.ai/code/session_01XYZ)_",
      }),
    ).toEqual(["pull request description has an AI tool's footer"]);
  });

  it("does not flag prose that mentions Claude", () => {
    const message = "docs: compare with Claude Code's review\n\nNo footer here.\n";
    expect(
      attributionProblems({ commits: [commit({ message })], body: "Uses Claude models." }),
    ).toEqual([]);
  });
});
